server:
  port: 8234

spring:
  datasource:
    username: ENC(AGa8GMvGChjAkY17AmQE4g==)
    password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)
    url: jdbc:mysql://192.168.10.145:17000/datum_platform_0.5.0?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

# 系统参数配置
system:
  config:
    # 公共组织信息
    publicOrgList:
      - identity: did:pid:lat1eqpf8vxz7m64j25mkmwk39t3xf8zeltxrr2nql
        host: 192.168.10.152
        port: 10033
      - identity: did:pid:lat1hlh4qhk9pv33wl62w3myhw2h4mcu4eyfxax4hs
        host: 192.168.10.153
        port: 10033
      - identity: did:pid:lat166gjn98vr5lvl3x2lsltsxjspq77arrp2szcfw
        host: 192.168.10.154
        port: 10033

# 单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.10.145:17100

# 节点网络设置
chain:
  platon:
    chainId: 2203181
    hrp: lat
    datumNetworkPayAddress: "0x263B1D39843BF2e1DA27d827e749992fbD1f1577"
    uniswapV2Router02: "0x4378dAF745E9053f6048c4f78c803f3bC8829703"
    voteAddress: "0xe525118e9DD588D75c2925F8DE01AFC4Fc22c391"
    voteDeployBlockNumber: "25461949"
    web3jProtocol: WS
    web3jAddresses: 8.219.126.197:6790
    chainName: "PlatON开发网"
    rpcUrl: https://devnetopenapi2.platon.network/rpc
    symbol: LAT
    blockExplorerUrl: https://devnetscan.platon.network/
    dexUrl: http://10.10.8.181:8080/
    tofunftUrl: https://tofunft.com/

