server:
  port: 10000

spring:
  datasource:
    username: ENC(AGa8GMvGChjAkY17AmQE4g==)
    password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)
    url: jdbc:mysql://192.168.10.145:17000/db_moirae_040?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

# 系统参数配置
system:
  config:
    # 公共组织信息
    publicOrgList:
      - identity: identity:4d7b5f1f114b43b682d9c73d6d2bc18e
        host: 192.168.10.147
        port: 10033
      - identity: identity:8003323d0d1248719be0d50e98e9666e
        host: 192.168.10.148
        port: 10033
      - identity: identity:7008f843ae69476590c3aab9fc888ec4
        host: 192.168.10.149
        port: 10033

# 单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.10.145:17100

# 节点网络设置
chain:
  platon:
    chainId: 2203181
    hrp: lat
    datumNetworkPayAddress: "0x263b1d39843bf2e1da27d827e749992fbd1f1577"
    uniswapV2Router02: "0x4378daf745e9053f6048c4f78c803f3bc8829703"
    web3jProtocol: WS
    web3jAddresses: 192.168.10.146:7789
    chainName: "PlatON开发网"
    rpcUrl: https://devnetopenapi2.platon.network/rpc
    symbol: LAT
    blockExplorerUrl: https://devnetscan.platon.network/
    dexUrl: http://10.10.8.181:8080/

