server:
  port: 8234

spring:
  datasource:
    username: ENC(AGa8GMvGChjAkY17AmQE4g==)
    password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)
    url: jdbc:mysql://192.168.10.145:17000/datum_platform_0.5.0?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

# 系统参数配置
system:
  config:
    # 公共组织信息
    publicOrgList:
      - identity: did:pid:lat1nj9h2mrwp0hq9wm0j9mtyc3zlm8uuw6wp5qpad
        host: 192.168.9.153
        port: 10033
      - identity: did:pid:lat1g83xnwcqc4uufpx9588muq0e98g93rlmpgx563
        host: 192.168.9.154
        port: 10033
      - identity: did:pid:lat1d8xw8d9ufue2dm5gg2mf9lxnundxff98xf7vah
        host: 192.168.9.155
        port: 10033
# 单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.10.145:17100

# 节点网络设置
chain:
  platon:
    chainId: 2203181
    hrp: lat
    datumNetworkPayAddress: "0x263B1D39843BF2e1DA27d827e749992fbD1f1577"
    uniswapV2Router02: "0x4378dAF745E9053f6048c4f78c803f3bC8829703"
    voteAddress: "0x857027b23F73F5823984d90550A39cAA6FA43A11"
    voteDeployBlockNumber: "27713101"
    web3jProtocol: HTTP
    web3jAddresses: 8.219.126.197:6789
    chainName: "PlatON开发网"
    rpcUrl: https://devnetopenapi2.platon.network/rpc
    symbol: LAT
    blockExplorerUrl: https://devnetscan.platon.network/
    dexUrl: http://10.10.8.181:8080/
    tofunftUrl: https://tofunft.com/
