server:
  port: 8234

spring:
  datasource:
    username: ENC(AGa8GMvGChjAkY17AmQE4g==)
    password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)
    url: jdbc:mysql://192.168.10.145:17000/datum_platform_0.5.0?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

# 系统参数配置
system:
  config:
    # 公共组织信息
    publicOrgList:
      - identity: identity:4d7b5f1f114b43b682d9c73d6d2bc18e
        host: 192.168.10.147
        port: 10033
      - identity: identity:8003323d0d1248719be0d50e98e9666e
        host: 192.168.10.148
        port: 10033
      - identity: identity:7008f843ae69476590c3aab9fc888ec4
        host: 192.168.10.149
        port: 10033

# 单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.10.145:17100

# 节点网络设置
chain:
  platon:
    chainId: 2203181
    hrp: lat
    datumNetworkPayAddress: "0x263B1D39843BF2e1DA27d827e749992fbD1f1577"
    uniswapV2Router02: "0x4378dAF745E9053f6048c4f78c803f3bC8829703"
    voteAddress: "0x2Ea91Cd38dA39c2a202D64cD9e41E3E3A74fb057"
    voteDeployBlockNumber: "10000"
    web3jProtocol: WS
    web3jAddresses: 8.219.126.197:6790
    chainName: "PlatON开发网"
    rpcUrl: https://devnetopenapi2.platon.network/rpc
    symbol: LAT
    blockExplorerUrl: https://devnetscan.platon.network/
    dexUrl: http://10.10.8.181:8080/

