server:
  port: 8234

spring:
  datasource:
    username: ENC(AGa8GMvGChjAkY17AmQE4g==)
    password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)
    url: jdbc:mysql://192.168.10.145:17000/datum_platform?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

# 系统参数配置
system:
  config:
    # 公共组织信息
    publicOrgList:
      - identity: did:pid:lat18vpuxh97dh52y6kr5csacuj9qv2c7qaem5ax8d
        host: 192.168.10.152
        port: 10033
      - identity: did:pid:lat12g9dw8f24e7vdnup982k2lwfjsxewpkkp5lqqu
        host: 192.168.10.153
        port: 10033
      - identity: did:pid:lat1gua5y4zpmf4pclrvvtfsywv6vph34xgwdqc2un
        host: 192.168.10.154
        port: 10033

# 单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.10.157:17100

# 节点网络设置
chain:
  platon:
    chainId: 2203181
    hrp: lat
    datumNetworkPayAddress: "0x263B1D39843BF2e1DA27d827e749992fbD1f1577"
    uniswapV2Router02: "0x4378dAF745E9053f6048c4f78c803f3bC8829703"
    voteAddress: "0x0a033cA8faA1cBB184d196a71A0BaeD76cE493cB"
    voteDeployBlockNumber: "26092260"
    didAddress: "0x279167d9767b10CEF88b9a81D9C912e475c0B75b"
    pctAddress: "0xFa2A71584740c749F1EF055741140833534504CD"
    credentialAddress: "0x6Afe474d2201525558b50D5D5a8544e88d222E05"
    web3jProtocol: HTTP
    web3jAddresses: 8.219.126.197:6789
    chainName: "PlatON开发网"
    rpcUrl: https://devnetopenapi2.platon.network/rpc
    symbol: LAT
    blockExplorerUrl: https://devnetscan.platon.network/
    dexUrl: http://10.10.8.181:8080/
    tofunftUrl: https://tofunft.com/
