server:
  port: 8234
  servlet:
    context-path: /rosettaflow
    encoding:
      charset: UTF-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.10.8.184:3306/db_rosettaflow?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 600000
  redis:
    host: 10.10.8.182
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
        max-wait: -1
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: RosettaFlow-Task-
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 系统参数配置
system:
  config:
    # 登录超时时间,单位: 毫秒
    loginTimeOut: 18000000000
    # 登录互踢模式： true-是,false-否
    kickMode: false
    # 是否是主服务: true-主服务,false-从服务
    masterNode: true
    # nonce存放时间，单位：秒
    nonceTimeOut: 300


grpc:
  client:
    carrier-grpc-server:
      address: 'static://192.168.10.146:4444'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext