server:
  port: 8234
  servlet:
    context-path: /rosettaflow
    encoding:
      charset: UTF-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123!
    url: jdbc:mysql://192.168.120.137:16000/db_moirae?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 600000
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: Moirae-Task-
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# 系统参数配置
system:
  config:
    # 登录超时时间,单位: 毫秒
    loginTimeOut: 18000000000
    # 登录互踢模式： true-是,false-否
    kickMode: false
    # nonce存放时间，单位：秒
    nonceTimeOut: 300000
    # 数据库数据批量更新
    batchSize: 1000
    # 公共组织信息
    publicOrgList:
      - identity: identity:6a0528ed26df40c9a9d5fef04c97525e
        host: 39.99.136.194
        port: 10033
      - identity: identity:ac8011c070d1445aaf26bc7a01627f9a
        host: 39.98.115.31
        port: 10033
      - identity: identity:e926ef630cd240018125a04822068f1e
        host: 39.101.198.154
        port: 10033
grpc:
  client:
    carrier-grpc-server:
      address: 'static://${system.config.publicOrgList[0].host}:${system.config.publicOrgList[0].port}'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
#单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.120.137:16100
#集群模式
#redisson:
#  model: CLUSTER
#  password: gasa123456
#  multiple-server-config:
#    node-addresses[0]: 10.10.8.173:6379
#    node-addresses[1]: 10.10.8.174:6379
