server:
  port: 10000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(AGa8GMvGChjAkY17AmQE4g==)
    password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)
    url: jdbc:mysql://192.168.10.145:17000/db_moirae_040_cd?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 600000
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: Moirae-Task-

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.moirae.rosettaflow.mapper.enums
# 系统参数配置
system:
  config:
    # 登录超时时间,单位: 毫秒
#    loginTimeOut: 1800000
    loginTimeOut: 180000000
    # 登录互踢模式： true-是,false-否
    kickMode: false
    # nonce存放时间，单位：秒
    nonceTimeOut: 300000
    # 公共组织信息
    publicOrgList:
      - identity: identity:6a9df99adf8e48ed94bed3b53f9ea4f7
        host: 192.168.9.152
        port: 10033

grpc:
  client:
    carrier-grpc-server:
      address: 'static://${system.config.publicOrgList[0].host}:${system.config.publicOrgList[0].port}'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
# 单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.10.145:17100
# 节点网络设置
chain:
  platon:
    chainId: 210309
    hrp: lat
    metisPayAddress: "0x7eb718524d1ecceef89196bc8315317bf8b5a05a"
    uniswapV2Router02: "0x26d637e206cc39942628421e7b0d6fb41db0bc06"
    web3jProtocol: WSS
    web3jAddresses: devnetopenapi.platon.network/ws
    chainName: "PlatON开发网"
    rpcUrl: https://devnetopenapi.platon.network/rpc
    symbol: LAT
    blockExplorerUrl: https://uatscan.platon.network:1443/




