server:
  port: 8234
  servlet:
    context-path: /rosettaflow
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
        secure: true

spring:
  profiles:
    active: dev