server:
  port: 8234
  servlet:
    context-path: /rosettaflow
    encoding:
      charset: UTF-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.10.8.184:3306/db_rosettaflow?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 600000
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: Moirae-Task-
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# 系统参数配置
system:
  config:
    # 登录超时时间,单位: 毫秒
    loginTimeOut: 18000000000
    # 登录互踢模式： true-是,false-否
    kickMode: false
    # nonce存放时间，单位：秒
    nonceTimeOut: 300000
    # 算法初始化文件
    algorithmFilepath: classpath:script/algorithm.csv
    # 数据库数据批量更新
    batchSize: 1000
    # redis中数据默认保存超时时间(毫秒)
    redisTimeOut: 86400000

grpc:
  client:
    carrier-grpc-server:
      address: 'static://192.168.9.151:8801'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

#单Redis节点模式
redisson:
  singleServerConfig:
    address: 10.10.8.176:6379

