server:
  port: 8234
  servlet:
    context-path: /rosettaflow
    encoding:
      charset: UTF-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.10.8.184:3306/db_rosettaflow?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 600000
  redis:
    cluster:
      nodes: xxxx.xxxx.xxxx.xxxx:6379
    password: ENC(xxxxxxxxxxxx)
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
        max-wait: -1

# 系统参数配置
system:
  config:
    # 登录超时时间,单位: 毫秒
    loginTimeOut: 1800000
    # 登录互踢模式： true-是,false-否
    kickMode: false
    # nonce存放时间，单位：秒
    nonceTimeOut: 300
    # 算法初始化文件
    algorithmFilepath: classpath:script/algorithm.csv
    # 数据库数据批量更新
    batchSize: 1000


grpc:
  client:
    carrier-grpc-server:
      address: 'static://192.168.9.151:8801'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

