server:
  port: 8234

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(AGa8GMvGChjAkY17AmQE4g==)
    password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)
    url: jdbc:mysql://192.168.10.145:17000/db_moirae_040?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 600000
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: Moirae-Task-

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.moirae.rosettaflow.mapper.enums
# 系统参数配置
system:
  config:
    # 登录超时时间,单位: 毫秒
    loginTimeOut: 18000000000
    # 登录互踢模式： true-是,false-否
    kickMode: false
    # nonce存放时间，单位：秒
    nonceTimeOut: 300000
    # 数据库数据批量更新
    batchSize: 1000
    # 公共组织信息
    publicOrgList:
      - identity: identity:e9eef460ea9c473993c6477915106eed
        host: 192.168.10.150
        port: 10033
      - identity: identity:3ddb63047d214ddd8187438a82841250
        host: 192.168.10.151
        port: 10033
      - identity: identity:f614f8ac21b44fe89926ad4f26ef5b07
        host: 192.168.10.152
        port: 10033

grpc:
  client:
    carrier-grpc-server:
      address: 'static://${system.config.publicOrgList[0].host}:${system.config.publicOrgList[0].port}'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
# 单Redis节点模式
redisson:
  password: 123456
  singleServerConfig:
    address: 192.168.10.145:17100
# 节点网络设置
chain:
  platon:
    chainId: 100
    hrp: lat
    metisPayAddress: lat1aad66x6tcq7l8dkk9l53fc29zf49l7qdqxnyv7
    web3jProtocol: WS
    web3jAddresses: 192.168.120.151:7789,192.168.120.151:7790




